name: 'Deploy Azure SQL Database schema'

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  deploy_database_job:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - uses: Azure/sql-action@v1
      with:
        server-name: 'bus-server545000.database.windows.net'
        connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
        dacpac-package: './database/dacpac/bus-db.dacpac'
