name: Deploy Python project to Azure Function App

on:
  push:
    branches:
      - main

env:
  AZURE_FUNCTIONAPP_NAME: azbusfunc
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'azure-function/python'
  PYTHON_VERSION: '3.9'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Install dependencies
      run: |
        python -m pip install --target=".python_packages/lib/site-packages" -r requirements.txt
        echo "" > requirements.txt
      working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

    - name: Output Environment Variables
      run: printenv

    - name: Output Working Directory
      run: |
        pwd
        ls -la ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

    - name: Debug Publish Profile
      run: echo "${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}"

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
